Order pdf renew
eccubevn/order-pdf-plugin pull request #1
Opened 2016-11-15 10:38 UTC by lqdung-lockon

2016-11-18 09:01 UTC, lammn commented on Event/CommonEvent.php
> +        $search = '/(<li\s+id="dropmenu"[\s\S]*)'; // Points to start the search.
don't use inline comment

2016-11-18 09:01 UTC, lammn commented on Event/CommonEvent.php
> +        // For old and new ec-cube version
group comment

2016-11-18 09:01 UTC, lammn commented on Event/CommonEvent.php
> +        $search .= '(<\/li>[\n\s]*<\/ul>)'; // The end of the dropdown section.
don't use inline comment

2016-11-18 09:01 UTC, lammn commented on Event/CommonEvent.php
> +        $search .= '([\s\S]*<form\s+id="dropdown\-form")/'; // Points to end the search.
don't use inline comment

2016-11-18 09:01 UTC, lammn commented on Event/OrderPdfLegacy.php
> +        } catch (\InvalidArgumentException $e) {
log error when catch

2016-11-18 09:01 UTC, lammn commented on OrderPdfEvent.php
> +    private function supportNewHookPoint()
Move this function to utils.

2016-11-18 09:01 UTC, lammn commented on Resource/doctrine/migration/Version201611111300.php
> +            foreach ($schemaFromMetadata->getTables() as $table) {
add code for remove sequence in postgresql

2016-11-21 04:14 UTC, lqdung-lockon commented on Resource/doctrine/migration/Version201611111300.php
> +            foreach ($schemaFromMetadata->getTables() as $table) {
Have not sequence table.

2016-12-09 07:44 UTC, ryo-endo requested changes

2016-12-09 07:44 UTC, ryo-endo commented on Resource/doctrine/migration/Version201611111300.php
> +        $classes = array(
can you use `$this->getMetadata` function ?

2016-12-09 07:44 UTC, ryo-endo commented on ServiceProvider/OrderPdfServiceProvider.php
> +        $admin->match('/plugin/order-pdf/download', '\\Plugin\\OrderPdf\\Controller\\OrderPdfController::download')
$admin->post ?

2016-12-09 07:44 UTC, ryo-endo commented on event.yml
> +    - [onAdminOrderRender, NORMAL]
onAdminOrderRender -> onAdminOrderIndexRender

2016-12-09 07:44 UTC, ryo-endo commented on PluginManager.php
> +        $this->backupLogo($app['config']);
necessary ? (because, install function done this)

2016-12-09 07:44 UTC, ryo-endo commented on PluginManager.php
> +        $this->rollBackLogo($arrConfig);
update. I would like to keep the logo file. (maybe, customized to the user's shop logo)

2016-12-09 07:44 UTC, ryo-endo commented on PluginManager.php
> +        $sourcePath = $config['template_realdir'].'/'.$this->logoName;
its not write in best practice...
put in plugin code dir.
i.e.) $config['template_realdir'].'/OrderPdf/'.$this->logoName;

2016-12-09 07:55 UTC, lqdung-lockon commented on Resource/doctrine/migration/Version201611111300.php
> +        $classes = array(
I do like the Maker plugin! Is it wrong?

2016-12-09 07:55 UTC, lqdung-lockon commented on ServiceProvider/OrderPdfServiceProvider.php
> +        $admin->match('/plugin/order-pdf/download', '\\Plugin\\OrderPdf\\Controller\\OrderPdfController::download')
Yes, I will fix it.

2016-12-09 07:56 UTC, lqdung-lockon commented on event.yml
> +    - [onAdminOrderRender, NORMAL]
I think the default is "index" so do not need.

2016-12-09 07:56 UTC, lqdung-lockon commented on PluginManager.php
> +        $sourcePath = $config['template_realdir'].'/'.$this->logoName;
Yes, I will fix it.

2016-12-09 08:19 UTC, ryo-endo commented on PluginManager.php
> +        $this->backupLogo($app['config']);
```
public function install($config, $app)
{
    // Backup logo.
    $this->backupLogo($app['config']);
}
```

```
public function enable($config, $app)
{
    // Backup logo.
    $this->backupLogo($app['config']);
    
    $this->migrationSchema($app, __DIR__.'/Resource/doctrine/migration', $config['code']);
}
```

`$this->backupLogo($app['config']);` is duplicated.
i think, its unnecessary in `function enable`.

2016-12-09 08:25 UTC, ryo-endo commented on PluginManager.php
> +        $this->rollBackLogo($arrConfig);
Update：
if (logo.png is exist) {
    don't overwrite logo file. (keep user's logo file)
} else {
   //not exist
   copy the logo.png
}

2016-12-12 03:10 UTC, kiy0taka requested changes

2016-12-12 03:10 UTC, kiy0taka commented on ServiceProvider/OrderPdfServiceProvider.php
> +        $app['config'] = $app->share($app->extend('config', function ($config) {
Use config.yml to define constants.
See http://ec-cube.github.io/plugin_bp_config#section-2

2016-12-12 03:53 UTC, ryo-endo requested changes
### [bug]
カレンダーが2重に表示されてしまいます。
他の画面と同じ表示・動きになるのが期待値です。
![image](https://cloud.githubusercontent.com/assets/16891862/21087532/0ed4fb40-c06a-11e6-8798-bad29383b6d4.png)

2016-12-12 04:04 UTC, ryo-endo commented on event.yml
> +    - [onAdminOrderRender, NORMAL]
"index" not means "default page" (like index.html).
it means ... "index search" "index card" "index page" ...index.

i'd like to rename to `onAdminOrderIndexRender` to clarify.

2016-12-12 04:11 UTC, ryo-endo commented on Resource/doctrine/migration/Version201611111300.php
> +        $classes = array(
i read code again.
sorry, its my mistake. no problem.

2016-12-12 04:11 UTC, ryo-endo commented on PluginManager.php
> +        $this->backupLogo($app['config']);
fix https://github.com/eccubevn/order-pdf-plugin/pull/3

2016-12-12 04:12 UTC, ryo-endo commented on PluginManager.php
> +        $this->rollBackLogo($arrConfig);
https://github.com/eccubevn/order-pdf-plugin/pull/3

2016-12-12 06:38 UTC, ryo-endo requested changes
### [bug ]
複数受注を選択して、帳票出力ができない。
(463e356 から発生している)

2016-12-12 06:58 UTC, ryo-endo requested changes

2016-12-12 06:58 UTC, ryo-endo commented on Resource/template/admin/order_pdf.twig
> +            $("#back").click(function (event) {
戻るの実装が簡易的すぎます。
いまの実装でも問題は起こらないのですが、他のページ（たとえば受注編集画面）と合わせてください。
難しい実装ではないので、修正お願いします。

2016-12-13 08:31 UTC, ryo-endo approved these changes

2016-12-14 02:30 UTC, closed without merging